### ISSUE TITLE
Use jest type instead of jasmine types

### ISSUE THREAD

**Issue by Robin-Hoodie** [briebug/jest-schematic#24]
**Is your feature request related to a problem? Please describe.**
As Jest types are built on top of It would probably be a better idea to use Jest types instead of the default Jasmine types Angular comes with. We're already adding `@types/jest` to `package.json`, but it doesn't seem like we're actually using it.

**Describe the solution you'd like**

After adding this schematic with `ng add`, we could, in addition to the current functionality

- Remove `@types/jasmine` from `package.json`
- Remove `@types/jasminewd2` from `package.json`
- Change `types: ["jasmine", "node"]` to `types: ["jest", "node"]` in `tsconfig.spec.json`

**Comment by strattonwhisler** [comment]
Thanks for the report.

I have a fix in progress for using `types: ["jest", "node"]` instead of `types: ["jasmine", "node"]` in `tsconfig.spec.json`.

Unfortunately, `@types/jasmine` and `@types/jasminewd2` cannot be removed without causing issues with E2E testing since Protractor is configured to use Jasmine. At the moment, Protractor doesn't support Jest (see https://github.com/angular/protractor/issues/3889). Looks like the Protractor team would be open to adding Jest support though (https://github.com/angular/protractor/issues/3889#issuecomment-282520791). Until then, this schematic will have to keep Jasmine around.

**Comment by Robin-Hoodie** [comment]
@inventer99 Is it not an option to use `types: ["jest", "jasmine", "node"]` in that case?

**Comment by strattonwhisler** [comment]
@Robin-Hoodie I see how my reply may have been confusing.

Your originally suggested solution for the `types` entry in `tsconfig.spec.json` is correct. e2e and unit tests use different `tsconfig.json` files, so the unit tests can utilize `types: ['jest', 'node']` while the e2e tests utilize `types: ['jasmine', 'jasminewd2', 'node']`. We don't need to merge the two.

My comment was in regard to the types packages (`node_modules`) for Jasmine rather than the `compilerOptions.types` . Since e2e tests use Jasmine, we need to keep the types/packages around, even though the unit tests no longer use them.

**Comment by schuchard** [comment]
I've looped this change into a larger PR. Please see if `ng add @briebug/jest-schematic@3.0.0-0` solves the issue

**Comment by HamzaMoiyadi** [comment]
Hey, 
I just installed version 3.1.0, which has the `jest` type added in the `tsconfig.spec.json` correctly, however I am still getting the following issue. Am I doing something wrong here?

![Screenshot_20210610_230754](https://user-images.githubusercontent.com/17302799/121571480-b3e85e80-ca40-11eb-97bb-1bdfcd9f3e94.png)
