### ISSUE TITLE
npm test fails due to improper types (string vs array) in angular.json

### ISSUE THREAD

**Issue by rkennel** [briebug/jest-schematic#72]
**Describe the bug**
``npm test`` fails due to improper types (string vs array) in angular.json

**To Reproduce**

1. ``ng new my-app``
2. ``ng add @angular-eslint/schematics``  
3. ``ng add @briebug/jest-schematic``
4. ``npm test``
```
Schema validation failed with the following errors:
  Data path "/polyfills" must be array.
```
5. fix test/polyfills to be string array instead of string 
6. ``npm test``
```
Schema validation failed with the following errors:
  Data path "/inlineStyleLanguage" must be array.
```

**Expected behavior**
Tests should have run successfully after step 4

**Desktop (please complete the following information):**
 - OS: Linux
 - Node version: v14.17.6
 - NPM 7.22.0
 - Angular CLI
 - @angular/core: "~12.2.0"

**Comment by ShaneYu** [comment]
I get exactly the same issue, I was doing the steps you've mentioned above identically.

I had to change both those properties under the test builder options to be arrays in order to get it working, but is a little odd as those properties everywhere else throughout the angular json file are single strings (not arrays).
